homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    binary_sensor.sw_motion_sensor_sensor_2_0:
      friendly_name: SE Motion Sensor
    binary_sensor.nw_motion_sensor_sensor_6_0:
      friendly_name: NW Motion Sensor

# Enables the frontend
frontend:

http:

# Checks for available updates
updater:
  reporting: no

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

notify me:
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
    name: pushover
  - platform: smtp
    name: emailer
    server: smtp.gmail.com
    port: 587
    sender: !secret email_username
    starttls: true
    username: !secret email_username
    password: !secret email_password
    recipient: !secret email_recipient

climate:
  platform: zwave

zwave:
  usb_path: /dev/ttyUSB-ZStick-5G
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/
  polling_interval: 60000

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    interval_seconds: 12
    consider_home: 180
    track_new_devices: False

sensor:
  - platform: template
    sensors:
      se_motion_sensor_battery:
        value_template: >-
          {% if states.binary_sensor.sw_motion_sensor_sensor_2_0 != None %}
            {{ states.binary_sensor.sw_motion_sensor_sensor_2_0.attributes.battery_level }}
          {% else %}
          {% endif %}
        unit_of_measurement: '%'
        friendly_name: "SE Motion Sensor Battery"
  - platform: template
    sensors:
      nw_motion_sensor_battery:
        value_template: >-
          {% if states.binary_sensor.nw_motion_sensor_sensor_6_0 != None %}
            {{ states.binary_sensor.nw_motion_sensor_sensor_6_0.attributes.battery_level }}
          {% else %}
          {% endif %}
        unit_of_measurement: '%'
        friendly_name: "NW Motion Sensor Battery"
  - platform: template
    sensors:
      fdlock_battery:
        value_template: >-
          {% if states.binary_sensor.front_door_lock_locked_4_0 != None %}
            {{ states.binary_sensor.front_door_lock_locked_4_0.attributes.battery_level }}
          {% else %}
          {% endif %}
        unit_of_measurement: '%'
        friendly_name: "Front Door Lock Battery"
#  - platform: template
#    sensors:
#      lock_beach_door_status:
#        value_template: >-
#          {%  elif is_state("sensor.front_door_lock_alarm_type_4_0", "1") %}
#            Locked By Home Assistant
#          {%  elif is_state("sensor.front_door_lock_alarm_type_4_0", "2") %}
#            Unlocked By Home Assistant
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "9") -%}
#            Deadbolt Jammed
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "18") -%}
#            Locked By Keypad
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "19") -%}
#            Unlocked By Keypad
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "21") %}
#            Locked By Key or Thumb Turn
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "22") %}
#            Unlocked By Key or Thumb Turn
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "24") %}
#            Auto Locked
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "25") %}
#            Auto Unlocked
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "27") %}
#            Auto-Relocked
#          {%- elif is_state("sensor.front_door_lock_alarm_type_4_0", "161") %}
#            Tamper
#          {%- else -%}
#            Unknown State: {{ states.sensor.front_door_lock_alarm_type_4_0.state }}
#          {%- endif %}
#        friendly_name: "Front Door Status"

camera:
  - platform: amcrest
    host: !secret camera_host
    username: !secret camera_username
    password: !secret camera_password
    name: "Front Door Camera"

shell_command:
  snapshot: !secret snapshot_template

script:
  burglar:
    alias: Burglar Alarm
    sequence:
      - delay:
          seconds: 1
      - service: shell_command.snapshot
        data:
          filename: /home/hass/snapshot1.jpg
      - delay:
          seconds: 1
      - service: shell_command.snapshot
        data:
          filename: /home/hass/snapshot2.jpg
      - delay:
          seconds: 1
      - service: shell_command.snapshot
        data:
          filename: /home/hass/snapshot3.jpg
      - delay:
          seconds: 1
      - service: shell_command.snapshot
        data:
          filename: /home/hass/snapshot4.jpg
      - delay:
          seconds: 1
      - service: shell_command.snapshot
        data:
          filename: /home/hass/snapshot5.jpg
      - delay:
          seconds: 1
      - service: notify.emailer
        data:
          title: 'Intruder alert!'
          message: 'Intruder alert!'
          data:
            images:
              - /home/hass/snapshot1.jpg
              - /home/hass/snapshot2.jpg
              - /home/hass/snapshot3.jpg
              - /home/hass/snapshot4.jpg
              - /home/hass/snapshot5.jpg

automation:
  - alias: SE Motion Alarm
    trigger:
      - platform: state
        entity_id: binary_sensor.sw_motion_sensor_sensor_2_0
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
    action:
      - service: notify.pushover
        data:
          title: "SW Motion Sensor Alarm"
          message: "Motion detected in SW corner of the living room."
      - service: script.burglar
  - alias: NW Motion Alarm
    trigger:
      - platform: state
        entity_id: binary_sensor.nw_motion_sensor_sensor_6_0
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
    action:
      - service: notify.pushover
        data:
          title: "NW Motion Sensor Alarm"
          message: "Motion detected in NW corner of the living room."
      - service: script.burglar
  - alias: Front Door Unlocked
    trigger:
      - platform: state
        entity_id: lock.front_door_lock_locked_4_0
        to: 'unlocked'
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
    action:
      service: notify.pushover
      data:
        title: "Front Door Unlocked"
        message: "Front door was unlocked without your phone on the network."
  - alias: Front Door Still Unlocked
    trigger:
      - platform: time
        minutes: /5
        seconds: 0
    condition:
      - condition: state
        entity_id: lock.front_door_lock_locked_4_0
        state: 'unlocked'
    action:
      service: notify.pushover
      data:
        title: "Front Door Still Unlocked"
        message: "Front door has been unlocked for at least 5 minutes."
  - alias: Front Door Deadbolt Jammed
    trigger:
      - platform: state
        entity_id: sensor.front_door_lock_alarm_type_4_0
        to: '9'
    action:
      service: notify.pushover
      data:
        title: "Front Door Deadbolt Jammed"
        message: "Front door was unable to lock because the deadbolt jammed."
  - alias: soft reset at 2:30am
    trigger:
      platform: time
      after: '2:30:00'
    action:
      service: zwave.soft_reset
  - alias: heal at 2:31am
    trigger:
      - platform: time
        after: '2:31:00'
    action:
      service: zwave.heal_network
